### ISSUE TITLE
Just curious: What happens if this is used on session with media_mode 'relayed'?

### ISSUE THREAD

**Issue by kennyki** [opentok/opentok-network-test#26]
I read in [FAQ](https://github.com/opentok/opentok-network-test#frequently-asked-questions-faq) that it should be used on routed OpenTok session, but what will happen if it's relayed?

Will it just be inaccurate, or will it not work at all?

Cheers

**Comment by bsrao** [comment]
@kennyki It will work but results will be inaccurate since it connects locally.

**Comment by kennyki** [comment]
I see. Thanks :-)
