### ISSUE TITLE
Video Packets Lost Always = 0 in VideoStatsListener

### ISSUE THREAD

**Issue by TeruyaHaroldo** [opentok/opentok-network-test#37]
I'm developing an simple application one to one in Android:
- One subscriber and one publisher. 
- Using Android 7.
- As the examples, I did and "re did" in many different forms.

In the event `onVideoStats` of the `SubscriberKit.VideoStatsListener`: 
- can get `stats.videoBytesReceived` normally.
- the `stats.videoPacketsLost` always has the '0' value.
- not using `SubscriberKit.AudioStatsListener`.

Am I doing something wrong? Somebody has the same problem?

**Comment by sampathdassanayake** [comment]
I have implemented this with a similar approach. We dont support audio only calls, so we are only concerned about the video stats. 

We upgraded our back end versions (JS) to support Safari. And with that we updated the opentok android sdk to 2.13. Now what I find is video stats listener event is not getting fired at all. Is anyone else experiencing this?

**Comment by msach22** [comment]
@HaroldoTeruya Thanks for filing this issue. We've raised it internally with our engineering team and I'll keep you posted on when this gets resolved.

**Comment by msach22** [comment]
@HaroldoTeruya The fix for this issue will be going with the 2.14.0 release. I will keep this issue open until we release 2.14.0.

**Comment by msach22** [comment]
@HaroldoTeruya Apologies for not updating the issue. This has been fixed with the 2.14.0 release which has been available for about two weeks 😄
