### ISSUE TITLE
VideoStats listener is not getting fired with Android SDK 2.13

### ISSUE THREAD

**Issue by sampathdassanayake** [opentok/opentok-network-test#38]
We are using this with a Tokbox safari project. With the Safari project we upgraded the android SDK to 2.13. But ever since that upgrade the network test is failing. The implementation is pretty much as in the sample except for the fact that we are not listening for audio stats, only video stats.

What I found was that Audio Stats event fires and returns results. But the video stats event doesnt even gets fired.

Is this a known issue?

**Comment by msach22** [comment]
@sampathdassanayake I'm running the Android 2.13.0 SDK locally and `videoStats` is firing for me. Could you verify that you've set the `videoStatsListener` for the subscriber in your app?

**Comment by msach22** [comment]
@sampathdassanayake Closing this issue b/c `videoStats` is firing correctly, but we're aware of the issue with `videoPacketsLost` always being set to 0. 
Please see #37
